project:
  type: website
  title: "Information Retrieval"
  output-dir: ../_site/fr

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"

  navbar:
    # background: primary
    search: true
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Cours"
        contents:
          - section: "Introduction"
            contents:
              - text: "Détails"
                href: ch1.qmd
              - text: "Synthèse"
                href: ch1r.qmd
              - text: "Quiz"
                href: ch1q.qmd
          - section: "Embeddings"
            contents:
              - text: "Détails"
                href: ch2.qmd
              - text: "Synthèse"
                href: ch2r.qmd
              - text: "Quiz"
                href: ch2q.qmd
          - section: "Embeddings Neuronaux"
            contents:
              - text: "Détails"
                href: ch3.qmd
              - text: "Synthèse"
                href: ch3r.qmd
              - text: "Quiz"
                href: ch3q.qmd
          - section: "Indexation"
            contents:
              - text: "Détails"
                href: ch5.qmd
              - text: "Synthèse"
                href: ch5r.qmd
              - text: "Quiz"
                href: ch5q.qmd
          - section: "Évaluation"
            contents:
              - text: "Détails"
                href: ch6.qmd
              - text: "Synthèse"
                href: ch6r.qmd
              - text: "Quiz"
                href: ch6q.qmd
      - section: "Examen"
        contents:
          - section: "chapitre 1"
            contents:


format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true

filters:
  - quizdown
