project:
  type: website
  title: "Information Retrieval"
  output-dir: ../_site/fr

website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Cours"
        contents:
          - section: "Chapitre 1 — Introduction"
            contents:
              - text: "Détails"
                href: ch1.qmd
              - text: "Synthèse"
                href: ch1r.qmd
          - section: "Chapitre 2 — Embeddings"
            contents:
              - text: "Détails"
                href: ch2.qmd
              - text: "Synthèse"
                href: ch2r.qmd
          - section: "Chapitre 3 — Embeddings Neuronaux"
            contents:
              - text: "Détails"
                href: ch3.qmd
              - text: "Synthèse"
                href: ch3r.qmd
          - section: "Chapitre 6 — Évaluation"
            contents:
              - text: "Détails"
                href: ch6.qmd
              - text: "Synthèse"
                href: ch6r.qmd
      - section: "Examen"
        contents:
          - section: "chapitre 1"
            contents:


format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true
  # pdf:
  #   toc: true
  # docx:
  #   toc: true

filters:
  - diagram
